### ISSUE TITLE
New things

### ISSUE THREAD

**Issue by beezisback** [brandonschapiro/TikTok-Reddit-Video-Maker#1]
Good Work!
I'm sorry to post here but I don't know how I can contact you

I recommend adding the option to save in a txt document all the topics created to keep track and not to create duplicate content.
topics should be taken from a bulk subreddit, without the need to specify each link for the clip. But to keep the existing option of creating a specific topic.
Another suggestion is to run the boot in loop, so that more clips can be made without entering the same settings every time we want to generate a clip .
you can also contact me on discord ambsd#8235

**Comment by brandonschapiro** [comment]
Thanks for the suggestions!

The original purpose for this project was to make creating these types of videos quick rather than pumping out a bunch of random videos, which is why the URL is specified each time. 
However, I'm currently working on automating the video creation + upload process and storing the post IDs in a text document is something I thought about. If everything goes according to plan, videos will be created and uploaded with 0 effort other than setting up a video creation and upload schedule.
